### ISSUE TITLE
The tooltip of sorting icon doesn't close after click

### ISSUE THREAD

**Issue by nva1805** [KevinVandy/mantine-react-table#312] opened 2024-04-15 03:26 UTC
### mantine-react-table version

1.3.4

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

When I click the sorting icon on one column multiple times and then move to another column's sort icon, the sorting tooltip doesn't hide; it remains visible. And when I continue to switch to another sort icon, all the tooltips start displaying. They can only be turned off when I hover over the icon and then hover out; otherwise, they all remain visible.

### Minimal, Reproducible Example - (Optional, but Recommended)

https://codesandbox.io/s/github/KevinVandy/mantine-react-table/tree/v1/apps/mantine-react-table-docs/examples/multi-sorting/sandbox?file=/src/TS.tsx (code sandbox of https://www.mantine-react-table.com/docs/guides/sorting#sort-direction)

### Screenshots or Videos (Optional)

![Screenshot 2024](https://github.com/KevinVandy/mantine-react-table/assets/162423526/3c453b04-1f7f-4091-baab-ca20199940a2)

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by alessandrojcm** [comment] 2024-04-15 09:02
Closing as duplicate of #186

**Closed as completed by alessandrojcm** 2024-04-15 09:02 UTC
Labels: bug, V1
