### ISSUE TITLE
Row actions throwing an `aria-hidden` error

### ISSUE THREAD

**Issue by ronny-lark** [KevinVandy/mantine-react-table#409] opened 2024-09-09 13:31 UTC
### mantine-react-table version

2.0.0-beta.3

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

I found that MRT is throwing a console error about aria-hidden when opening the row actions menu.
You can see this error by opening any row actions menu and looking at the console.
https://v2.mantine-react-table.com/docs/guides/row-actions

This happen when implementing a custom actions component or using the built-in menu and only providing options.

This does not happen with Mantine's menu, so I must assume it's something in the table composition. Perhaps something between the menu's state and table memoization?

### Minimal, Reproducible Example - (Optional, but Recommended)

See tables with row actions in your own documentation.

https://v2.mantine-react-table.com/docs/guides/row-actions

### Screenshots or Videos (Optional)

![image](https://github.com/user-attachments/assets/dae34bcb-c8b6-407c-8d25-6e449f28965a)

### Do you intend to try to help solve this bug with your own PR?

No, because I do not have time to dig into it

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by alessandrojcm** [comment] 2024-11-04 17:07
Closing as duplicate of #397

**Closed as completed by alessandrojcm** 2024-11-04 17:07 UTC
